### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by manelcecs** [manelcecs/scrume-front#28]
# Descripción
Se requiere implementar la gestión por parte del usuario, de sus datos en la aplicacion. Podrá ver toda su información, exportarla así como tener derecho al olvido.

## CheckList
- [x] Botón para ver los datos personales.
- [x] Botón para exportar los datos del usuario.
- [x] Botón para borrarse de la aplicación.

##Aceptación
- [x] Puedo ver mis datos
- [x] Puedo exportar mis datos
- [x] Puedo borrar todos mis datos y no volver a acceder a la aplicación

**Comment by EzequielPJ** [comment]
- [ ] Css responsive
- [ ] Deslogear y actualizar la barra horizontal

**Comment by EzequielPJ** [comment]
- [ ] Resolvers
