### ISSUE TITLE
Notificaciones

### ISSUE THREAD

**Issue by manelcecs** [manelcecs/scrume-front#31]
# Descripción
Como usuario de la aplicación quiero ver las notificaciones que tenga en el sistema, como las alertas de los eventos de Scrum como la realización de las dailies. Al verlas, puedo desestimarlas y no las volveré a ver.

## CheckList
- [x] Puedo ver mis notificaciones
- [x] Puedo desestimar mis notificaciones
- [x] Veo el formulario daily cuando la notificacion es de una daily.
- [x] Mejorar el rendimiento de las consultas a BBDD para que sea más eficiente y coherente.

## Aceptación
- [x] Puedo ver mis notificaciones
- [ ] Puedo desestimar mis notificaciones (pero mis compañeros mantienen las suyas)
- [x] Si mi notificacion es de una daily, puedo rellenarla

**Comment by jualorper** [comment]
@EzequielPJ Cuando hagas el apartado "Mejorar el rendimiento de las consultas a BBDD para que sea más eficiente y coherente." me puedes avisar y te puedo ayudar que lo tengo ya hecho y se podría resolver en pocos minutos.

**Comment by EzequielPJ** [comment]
@jualorper Si claro, lo tenia en cuenta ya que tu al final pillaste esa tarea literalmente. Seguramente mañana si puedes te avise ya que la parte de que te lleguen las notificaciones ya esta completa. Y gracias por el aviso.

**Comment by jualorper** [comment]
Okey. Mañana estaré todo el día así que avísame cuando tu puedas.
