### ISSUE TITLE
Menús Laterales

### ISSUE THREAD

**Issue by manelcecs** [manelcecs/scrume-front#36]
### Descripción
Se requiere corregir el comporamiento de los menús laterales (navegación y notificaciones).

### Checklist

- [x] Recargar la información de la navegación tras login/logout
- [x] Actualizar la información del bloque notificaciones (invitacion)
- [x] Actualizar la información del bloque notificaciones (alertas)
- [x] Mejorar el rendimiento del bloque notificaciones (invitacion)
- [x] Mejorar el rendimiento del bloque notificaciones (alertas)

### Aceptación

- [ ] Veo 'Mis equipos' y 'Mis tareas' al hacer login.
- [ ] No veo 'Mis equipos' y 'Mis tareas' al hacer logout
- [ ] Cuando cambia el icono de notificación, puedo verla

**Comment by jualorper** [comment]
En mi tarea de mejorar notificaciones ya tengo hecho el apartado de actualizar el bloque de notificacaciones. Me asigno esta tarea porque el resto de la checklist es muy sencilla con lo que he hecho.
